language: csharp
mono: none
dotnet: 2.1.502
script:
 - dotnet restore
 - dotnet test ConversorDeMoedas.services.Test/ConversorDeMoedas.Services.Test.csproj
 - dotnet test ConversorDeMoedas.Domain.Test/ConversorDeMoedas.Domain.Test.csproj
 - dotnet test ConversorDeMoedas.Infrastructure.Test/ConversorDeMoedas.Infrastructure.Test.csproj
 - dotnet build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master